site_name: Istio 0 to 60 Labs
repo_url: https://github.com/tetratelabs/istio-0to60
theme:
  name: material
  custom_dir: overrides
  logo_light_mode: assets/tetrate-logo-white.png
  logo_dark_mode: assets/tetrate-logo-black.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - content.code.copy
#    - navigation.tabs
extra_css:
  - css/custom.css
nav:
  - environment.md
  - install.md
  - sidecar-injection.md
  - discovery.md
  - the-app.md
  - ingress.md
  - ingress-gwapi.md
  - dashboards.md
  - security.md
  - traffic-shifting.md
  - traffic-shifting-gwapi.md
  - circuit-breakers.md
  - Summary: summary.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: artifacts
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - toc:
      permalink: true
plugins:
  - search
  # https://mkdocs-macros-plugin.readthedocs.io/en/latest/
  - macros
extra:
  istio:
    version: 1.21.1
